# Generated by Django 2.2.5 on 2019-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191202_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vessel',
            field=models.BooleanField(default=False),
        ),
    ]
