# Generated by Django 2.2.5 on 2020-01-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('decks', '0002_auto_20200114_1159'),
        ('accounts', '0005_auto_20191209_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clusters',
            field=models.ManyToManyField(to='decks.Cluster'),
        ),
        migrations.AddField(
            model_name='user',
            name='operator',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to='decks.Operator'
            ),
        ),
    ]
