# Generated by Django 2.2.5 on 2020-01-16 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('decks', '0002_auto_20200114_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='is_managed',
            new_name='is_manned',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='type',
        ),
        migrations.DeleteModel(
            name='ClusterType',
        ),
    ]
