# Generated by Django 2.2.5 on 2020-01-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('decks', '0003_auto_20200116_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cluster',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deck',
                to='decks.Cluster'
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='deck',
            name='is_manned',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='is_offshore',
            field=models.BooleanField(),
        ),

        migrations.AlterField(
            model_name='deck',
            name='operator',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deck',
                to='decks.Operator'
            ),
            preserve_default=False,
        ),
    ]
