# Generated by Django 2.2.5 on 2020-01-21 10:41

import decks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20200121_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='position_latitude',
            field=models.FloatField(validators=[decks.validators.validate_position_latitude]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='position_longitude',
            field=models.FloatField(validators=[decks.validators.validate_position_longitude]),
        ),
    ]
