# Generated by Django 2.2.5 on 2020-01-18 12:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectiontype_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', django.contrib.postgres.fields.jsonb.JSONField()),
                ('groups_preview', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='inspections.Inspection')),
            ],
        ),
    ]
