# Generated by Django 2.2.5 on 2020-01-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20200118_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='is_archive',
            new_name='is_archived',
        ),
    ]
