# Generated by Django 2.2.5 on 2020-02-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_auto_20200123_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
