# Generated by Django 2.2.5 on 2020-02-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_auto_20200217_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
