# Generated by Django 2.2.5 on 2020-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20200218_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='color_set',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='values_set',
            field=models.TextField(blank=True),
        ),
    ]
