# Generated by Django 2.2.5 on 2020-03-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_auto_20200225_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='color_set',
            new_name='colors_set',
        ),
    ]
